datamodule:
  dataset_path: ./data/Custom_smplx/
  data_list: ./lib/dataset/custom_train.csv
  cache_path: ${starting_path}
  num_workers: 16
  batch_size: 16 #used to be 16
  points_per_frame: 2000
  load_img: false
  load_cache: false
  load_surface: false
  load_res: 1024