defaults:
  - datamodule: renderpeople
  - network: lbs 
  - network: shape
  - network: disp
  - network: norm
  - network: tex
  # - network: offset

hydra:
  run:
    dir: outputs/${expname}/

expname: coarse
# resume: false
resume: true
starting_path: 'outputs/coarse/checkpoints/last.ckpt'
eval_mode: interp
seed: 42
agent_tot: 1
agent_id: 0

trainer:
  max_epochs: 300
  gradient_clip_val: 0.1
  check_val_every_n_epoch: 1
  deterministic: true
  gpus: -1
  # gpus: 2
  log_every_n_steps: 300
  accelerator: 'ddp'
  profiler: 'simple'

model:
  stage: coarse
  dim_shape: 64
  dim_detail: 64
  dim_color: 64

  deformer:
    _target_: lib.model.deformer.ForwardDeformer
    # _target_: lib.model.fast_deformer.ForwardDeformer
    max_steps: 50
    # align_corners: true
    # skinning_mode: mlp
    # res: 64
    # z_ratio: 4
    # global_scale: 1.2
    # soft_blend: 20
    # cvg: 1e-4
    # dvg: 5e-1
    
  optim:
    lr: 1e-3
    lr_dis: 1e-3

  nepochs_pretrain: 1
  lambda_bone_occ: 1
  lambda_bone_w: 10
  lambda_disp: 10
  lambda_lbs: 1
  lambda_offset: 0
  lambda_reg: 1e-3
  lambda_reg_color: 1e-3
  lambda_gan: 0
  lambda_gan_color: 0
  lambda_color: 1     # 给color的 gt loss加的权重，本来只有normal时，该loss不用加权重（总loss中可以有一项系数为1）

  use_gan: false
  use_gan_color: false
  volume_rendering: false
  
  ray_tracer:
    n_secant_steps: 8
    max_points: 500000 
    check_cube_intersection: false
    depth_range: [0,2]
    n_steps: [128,129]